apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ergo.fullname" . }}-config
  labels:
    {{- include "ergo.labels" . | nindent 4 }}
data:
  ircd.yaml: |
{{ .Values.ergo.config | toYaml | indent 4 }}
  ergo.motd: |
{{ .Values.ergo.motd | indent 4 }}
