apiVersion: v1
kind: Service
metadata:
  name: {{ include "ergo.fullname" . }}
  labels:
    {{- include "ergo.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.hostname | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: ircs
    port: 6697
    targetPort: ircs
    protocol: TCP
  - name: websocket
    port: 443
    targetPort: websocket
    protocol: TCP
  selector:
    {{- include "ergo.selectorLabels" . | nindent 4 }}
