apiVersion: v2
name: ergo
description: A Helm chart for Ergo IRC server
type: application
version: 0.1.0
appVersion: "2.15.0"
keywords:
  - irc
  - chat
  - ergo
home: https://ergo.chat/
sources:
  - https://github.com/ergochat/ergo
maintainers:
  - name: GeertJohan
